### ISSUE TITLE
wndchrm train crash

### ISSUE THREAD

**Issue by barcoyou** [wnd-charm/wnd-charm#34] opened 2014-07-13 06:26 UTC
After successfully compiling the project, when I run "wndchrm train /path/to/dataset dataset.fit I got the following crash:

./wndchrm train ~/Downloads/AMC-141-R/ test.fit
Processing directory '/home/barco/Downloads/AMC-141-R'
Adding '/home/barco/Downloads/AMC-141-R/AMC-141-R--001-macurato.sig' for sig calc.
processing '/home/barco/Downloads/AMC-141-R/AMC-141-R--001-macurato.sig' (index 0).
wndchrm: Eigen/src/Core/DenseCoeffsBase.h:337: Eigen::DenseCoeffsBase<Derived, 1>::Scalar& Eigen::DenseCoeffsBase<Derived, 1>::operator()(Eigen::DenseCoeffsBase<Derived, 1>::Index, Eigen::DenseCoeffsBase<Derived, 1>::Index) [with Derived = Eigen::Map<Eigen::Matrix<double, -1, -1, 1>, 1>; Eigen::DenseCoeffsBase<Derived, 1>::Scalar = double; Eigen::DenseCoeffsBase<Derived, 1>::Index = int]: Assertion `row >= 0 && row < rows() && col >= 0 && col < cols()' failed.
Aborted (core dumped)

**Comment by igg** [comment] 2015-01-07 20:02
Unless we hear otherwise, we're going to assume this is a duplicate of issue 39, and consider the matter closed.

**Closed** 2015-01-07 20:11 UTC
